### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by roryprimrose** [doximity/vital#16]
This framework looks great. Please add bower support and include the scss files in the package

**Comment by bodytaing** [comment]
Currently focusing on a ruby gem, but once that's released we will work on a bower and npm release. We're also open to accepting pull requests for the bower install if you'd like to create one 😁

**Comment by bodytaing** [comment]
@roryprimrose We're reshuffling, NPM & Bower will get priority over a ruby gem. Expect something within the next several weeks (fingers crossed).
