### ISSUE TITLE
`nav` styling appears to be too greedy

### ISSUE THREAD

**Issue by rspieker** [doximity/vital#18]
The `nav` styling is very greedy, as currently it will target all `<nav>` elements throughout the page and turn these into a horizontal menu.
Judging from the [file/position where it resides](https://github.com/doximity/vital/blob/master/source/stylesheets/_header.sass#L26) I think it may have been intended to end up within the `.header` scope.

Otherwise perhaps adding a class on its own would greatly reduce the amount of overrides one has to write, though the downside is that this would break the style for people relying on all `<nav>`-elements to end up as an hierarchical horizontal menu.

**Comment by bodytaing** [comment]
This is a good point. Let me review https://github.com/doximity/vital/pull/19 - I think what we might also do is allow people who are relying on https://github.com/doximity/vital/pull/3 to keep using the original release url in addition to adding separate versioning urls.

**Comment by bodytaing** [comment]
Resolved in release v1.0.1.
