### ISSUE TITLE
"Col-3-5" CSS Class does not work

### ISSUE THREAD

**Issue by whitef0x0** [doximity/vital#35]
The space css class does not create columns of proper width for 5-columned rows. I've tested this on Chrome 55.0 with Mac OSX El Capitan. It seems as though col-3-5 creates columns of col-1-5 width. If this is intended it should be clearly marked on the documentation at vitalcss.com.

Example:

```
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.rawgit.com/doximity/vital/v1.2.1/dist/css/vital.min.css">
  </head>
  <body>
    <div class="row">
      <div class="col-1-5 space">
      <div class="col-3-5"> Some Content Here </div>
      <div class="col-1-5 space">
    </div>
  </body>
</html>
```

**Comment by whitef0x0** [comment]
ping @bodytaing

**Comment by bodytaing** [comment]
`col-3-5` does not actually exist. The `col-1-5` denomination was originally created for an even spaced denomination. However, because `autogrid` already creates unlimited amounts of evenly spaced columns, I may add `col-3-5` denominations in the next version.

**Comment by bodytaing** [comment]
Updated documentation in: https://github.com/doximity/vital/pull/37
